### ISSUE TITLE
Need load conditions for vehicle/possess states.

### ISSUE THREAD

**Issue by volostyle** [Snakybo/Clicked#117]
Title says it all. I'm running into issues on fights like Occulus when I'm controlling the drakes. Sometimes the keybinds work, sometimes they don't. Are you able to add load conditions for when you are in a vehicle? The other issue I'm seeing is when I'm MC'd or Possessed, for example in the Drak'theron Keep dungon, on the last boss. Sometimes my abilities don't work there. But that fight doesn't consider you in a vehicle, it's almost like a shapeshifted form.

**Comment by medtryx** [comment]
I think this is related to this enhancement request as well.  While soaring, you are not considered in a vehicle, therefore your Clicked macros with the same keybinds as actionbar 1 are what fire when you try to use the soar abilities on the action bar you switch to.

**Comment by Snakybo** [comment]
For the Soar abilities you can use the "Flying" macro condition and bind like anything else.

The vehicle and MC issue is its own problem with its own set of challenges, Clicked bindings are disabled while in a vehicle or while MC-ed because in almost all circumstances your action bar gets replaced with a few custom abilities.

It'd be very cumbersome to require you to create bindings every time you enter a new type of vehicle for the first time. Since your primary action bar gets replaced with these buttons by default, I've opted to disable Clicked bindings and allow you to use the primary action bar instead, you could assign keybinds to those buttons which will be used when in a vehicle.

I agree there may be some instances where Clicked bindings would be better suited for vehicle buttons, however since there is no way to change active bindings in combat, it isn't really possible to make this function as I'd like it to.

**Comment by medtryx** [comment]
> 

I didn't even consider that option, as while I realized it was not functioning as a vehicle, I was still thinking as it in terms of being a vehicle. Considering most of my keybinds are for druids and all their forms, with form conditionals, I should have thought of that first.  Thanks for pointing that out. Will make things much easier!
