### ISSUE TITLE
Feature Request - able to edit a clicked data dump file offline and re-import 

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#135]
## Is your feature request related to a problem?
sometimes uynable to quickly/easily find issues and fix 

## Describe the solution you'd like
I'd like the ability to take the /cc dump output, edit the file, then import back into clicked

## Describe alternatives you've considered
slogging through the ui to edit.

**Comment by jermoo** [comment]
OR at least a way to edit a text file directly and import back to overwrite. It's a major pita to update modifier keys on all of the binds. Unless there's an easier way?
I'm about at the point of needing to delete the profile and re-create from scratch. 
tnx.

**Comment by Snakybo** [comment]
The debug output is not formatted in a way that allows for ingestion, so that's definitely out of scope for the time being.
For your specific issue, you can use this command to quickly update your **entire** profile:

Replace the `from` and `to` values depending on what you want to replace. _I recommend you back-up your profile first in case something goes wrong._

```
/run local from="CTRL";local to="ALT"; for _, b in Clicked:IterateConfiguredBindings() do b.keybind = b.keybind:gsub(from, to) end; Clicked:ReloadActiveBindings()
```
