### ISSUE TITLE
Mouseover Soulstone won't work on a dead ally in combat. It casts on me instead.

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#158]
### Describe the bug

I have a mouseover macro for Soulstone and it works fine when casting on another living player or on myself. If I try to cast it on a dead player, it instead casts it on me.

The macro is made with the "Cast spell on a unit frame" type of macro and I am only attempting to target unit frames when using it.

### Clicked Version

1.10.3 WARLOCK

### World of Warcraft Flavor

Dragonflight

### Lua Errors

There are no lua errors.

### Reproduction Steps

1. Cast Soulstone on a dead ally
2. Be confuse as to why it casts on you instead

### Screenshots

[https://i.imgur.com/YGcv13P.png](https://i.imgur.com/YGcv13P.png)
[https://i.imgur.com/vGl6tZU.png](https://i.imgur.com/vGl6tZU.png)
[https://i.imgur.com/vrFChdG.png](https://i.imgur.com/vrFChdG.png)
[https://i.imgur.com/ZLAyDW0.png](https://i.imgur.com/ZLAyDW0.png)
[https://i.imgur.com/F2F0Yi5.png](https://i.imgur.com/F2F0Yi5.png)

**Comment by jermoo** [comment]
change your targeting to macro target, and uncheck unit target. set your macro target to @mouseover, friendly, dead.

**Comment by gotex007** [comment]
It tells me [this](https://i.imgur.com/CaU40r9.png) and just makes the person my target when I click on them without doing anything else.

Another problem is that I still need it to work on a living target if I want to soulstone them too.

**Comment by Snakybo** [comment]
Do you perhaps have the self-cast modifier set to SHIFT in the interface settings?

**Comment by gotex007** [comment]
No. I do not have a modifier set. Even when I change it to ONLY cast on a friendly, dead target it still casts on me instead of them when they're dead.

**Comment by KatAKlettke** [comment]
I have the same issue. Soulstone is set to cast on left-click on the unit frame, target needs to be friendly and dead, yet it casts on me when i click on the downed tank/healer.

**Comment by lowpita** [comment]
Hey. I have this same issue without having self-cast enabled on blizzard's end. A work-around to this is to target the player who you want to cast the soulstone then press the clicked's keybind for it, only while in combat. Out of combat it does the normal behaviour.

**Comment by Snakybo** [comment]
So I looked into this a bit and got almost the same behavior, for me it actually just doesn't work if the target is dead even out of combat, but only when I have a target selected. If there is no target selected, it works fine.

I was able to reproduce this issue using the native Click Casting system, and even manually typing `/cast [@mouseover] Soulstone` in chat.

There is a very similar bug going on with a few other spells at the moment, I know about at least Divine Toll for Paladins not working correctly with `@mouseover` macros, because it will just go on the selected target. This is likely that same issue.

Unfortunately, there is nothing I can do about this as it's a bug on Blizzard's side. What I did to fix Divine Toll myself was to create a custom macro with the following contents:

```
/target [@mouseover]
/cast [@target] Divine Toll
/targetlasttarget
```

You can replace the Divine Toll in there with Soulstone, which _should_ work. I did not have time to test this myself at the moment, but I am fairly certain it will work as it works for Divine Toll.
```
/target [@mouseover]
/cast [@target] Soulstone
/targetlasttarget
```
