### ISSUE TITLE
Failed to load Macro Conditions for Druid

### ISSUE THREAD

**Issue by threedee** [Snakybo/Clicked#186]
### Describe the bug

An Error is created in LocaleUtils.llua Line 753
I dont know lua. But it seems that the addon tries to do a string format with a nil value. A check if name is not nil around that and the insert to the table seems to fix the problem for me.
At least I am now getting the macro conditions

### Clicked Version

Clicked 1.14.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

Click on Macro conditions for a spell on a druid. Lvl 13. Error is thrown. No Macro Conditions shown.

**Comment by zebus** [comment]
Getting the same bug in classic as well, since I have next to no coding knowledge I just tried commenting out line 753 and it let the tab load, however all the options on the form conditional dropdown are blank.

I use trial and error to figure out which option is which so works as a tempt fix tho lol

**Comment by zebus** [comment]
Nevermind, it wasn't a temp fix. Worked for bear, but I just learned catform and if I select the empty box that should correspond to cat (2) it unloads it and makes it unusable.

**Comment by Snakybo** [comment]
Sorry for the delay, should be fixed in the next release! :)
