### ISSUE TITLE
Clicked binding colliding with regular actionbar binding

### ISSUE THREAD

**Issue by tbuehlmann** [Snakybo/Clicked#19]
Not sure whether this is a bug or a feature, maybe @Snakybo can shed some light:

I have a regular actionbar binding on 1 for the Druid's Wrath spell. Now I added a Clicked binding for Regrowth with target="Mouseover target" on 1. The Regrowth binding works but the regular Wrath binding stopped working, so the Clicked binding seems to have priority on the 1 key.

Is this intended? That way I wouldn't be able to have different things on the same key when not using Clicked for both.

**Comment by Snakybo** [comment]
Hi!

You could accomplish something like this by using the "Unit Frame" target type, that one is a bit unique and will only override a keybinding when you're hovering over a unit frame.

Outside of that unfortunately due to the way the game works that's not possible when using any other target types. When configuring a keybind within Clicked it will override any action bar buttons that may be listening for that keybind.

**Comment by tbuehlmann** [comment]
I just tried using the Unit Frame target and the behaviour seems identical. Do you know how Clique is doing it? I can have a Clique binding **and** use the actionbar binding.

In the meantime, I added Clicked bindings mirroring my actionbar bindings, so that I still see the actionbar icons but it's really just for displaying. It's a bit cumbersome, but works.
