### ISSUE TITLE
Bind Vehicle keys

### ISSUE THREAD

**Issue by twin2** [Snakybo/Clicked#34]
## Is your feature request related to a problem?
Im using clicked for all my keys. when entering vehicles that means i need to click the action bars because 1234 don't default to those keys.

## Describe the solution you'd like
Not sure of the best solution, but either being able to bind the vehicle keys if that is doable. or have the addon bind 1234 to the vehicle when you are in one.  

## Describe alternatives you've considered
None, i click with mouse for now.

**Comment by Snakybo** [comment]
Yeah this is mostly intentional, what I personally do is bind my primary action bar to 1234567890-= and keep it empty so when I enter a vehicle I can use those buttons.

I don't think it's possible to automatically bind action bar buttons due to addons being able to create custom action bars and I can't support every action bar addon out there so I don't think I can do anything about this except for the current solution which just unlocks all bindings when in a vehicle.

**Comment by twin2** [comment]
Got it! thanks for the swift reply!

Im not using any addon for my actionbars so cant leave it empty, but i will just bind 1-5 on it. that should do it!

Great work with this addon!

Stay safe!
